version: "3"

services:
  app:
    container_name: gunma_backend_app
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file: .env

  db:
    container_name: gunma_backend_db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - db-store:/var/lib/postgresql/data
    restart: always

volumes:
  db-store:
