// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Gunma-Dots-to-Code/Gunma-Backend/internal/controller"
	"github.com/Gunma-Dots-to-Code/Gunma-Backend/internal/db"
	"github.com/Gunma-Dots-to-Code/Gunma-Backend/internal/repository"
	"github.com/Gunma-Dots-to-Code/Gunma-Backend/internal/router"
	"github.com/gofiber/fiber/v2"
)

// Injectors from wire.go:

func Wire() *fiber.App {
	gormDB := db.NewDB()
	userRepository := repository.NewUserRepository(gormDB)
	userController := controller.NewUserController(userRepository)
	categoryRepository := repository.NewCategoryRepository(gormDB)
	categoryController := controller.NewCategoryController(categoryRepository)
	questionRepository := repository.NewQuestionRepository(gormDB)
	questionController := controller.NewQuestionController(questionRepository)
	answerRepository := repository.NewAnswerRepository(gormDB)
	answerController := controller.NewAnswerController(answerRepository)
	app := router.NewRouter(userController, categoryController, questionController, answerController)
	return app
}
